version: '3'

services:
  db:
    image: 'postgres:11.0'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:6.0'
    command: redis-server
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  redis:
  postgres:
